### PR TITLE
Upgrade Yew to 0.21

### LINKED ISSUE #31: Upgrade to Yew 0.21
Tested locally, no trouble after running `cargo update`. 

If you don't run `cargo update`, you might encounter this issue: https://github.com/yewstack/yew/issues/3366 - I did.

Given the upstream version change + breaking changes in #30, I'd like to combine them both in our next release.

This might be a good time to revisit #23.

### PR DESCRIPTION
**Pull request by isosphere**
#31

You must run `cargo update`.

### CODE REVIEW

**Comment by dricair** [comment]
I tried your branch but I have an error I cannot explain for now, when launching `trunk serve` from the `example/basics` directory.

```
   Compiling yew v0.21.0
error[E0277]: the trait bound `implicit_clone::unsync::IMap<_, _>: From<indexmap::IndexMap<K, V>>` is not satisfied
   --> /home/username/.cargo/registry/src/index.crates.io-6f17d22bba15001f/yew-0.21.0/src/html/conversion/into_prop_value.rs:216:20
    |
216 |         IMap::from(self)
    |         ---------- ^^^^ the trait `From<indexmap::IndexMap<K, V>>` is not implemented for `implicit_clone::unsync::IMap<_, _>`
    |         |
    |         required by a bound introduced by this call
    |
    = help: the following other types implement trait `From<T>`:
              <implicit_clone::unsync::IMap<K, V> as From<indexmap::map::IndexMap<K, V>>>
              <implicit_clone::unsync::IMap<K, V> as From<std::rc::Rc<indexmap::map::IndexMap<K, V>>>>
              <implicit_clone::unsync::IMap<K, V> as From<&'static [(K, V)]>>

For more information about this error, try `rustc --explain E0277`.
error: could not compile `yew` (lib) due to previous error
2023-10-01T16:23:43.328224Z ERROR ❌ error
error from HTML pipeline
```

I am using Rust 1.72.1

What is strange is that I do not have this error if I create a new yew project and launch it, so it might be due to some dependency, but I don't know how to find it.

**Comment by isosphere** [comment]
> I am using Rust 1.72.1
> 
> What is strange is that I do not have this error if I create a new yew project and launch it, so it might be due to some dependency, but I don't know how to find it.

Did you see my comment above? 😉

> You must run `cargo update`.

**Comment by dricair** [comment]
I did, but I executed `cargo clean`, I thought it would do the job. I agree that `cargo update` does the job !
